apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: instagramservice
  namespace: instagram
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: instagramservice
      labels:
        app: instagramservice
    spec:
      serviceAccountName: instagram-account
      automountServiceAccountToken: false
      containers:
      - image: nkrokhmal/instabot
        name: instabot
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: 20m
          limits:
            cpu: 100m
        ports:
        - containerPort: 55555


  
