apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: instagramservice
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: instagramservice


