apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-backend
  namespace: default
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: nkrokhmal/flask-backend:1
        ports:
        - name: flask-backend
          containerPort: 6666
