apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-site
  namespace: default
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask-site
    spec:
      containers:
      - name: flask
        image: nkrokhmal/flask:2
        ports:
        - name: flask-site
          containerPort: 5000
      
