apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: instagram-rb 
  namespace: instagram
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-reader
subjects:
- kind: ServiceAccount
  name: instagram-account
  namespace: instagram
- kind: ServiceAccount
  name: default
  namespace: default
