apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: monitoring
spec:
  minReadySeconds: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:6.3.0
        name: logstash
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: logstash-config-volume
          mountPath: /usr/share/logstash/config
        - name: logstash-pipeline-volume
          mountPath: /user/share/logstash/pipeline
      volumes:
      - name: logstash-config-volume
        configMap:
          name: logstash-config
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logstash-config
          items:
          - key: logstash.conf
            path: logstash.conf




