apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
  namespace: default
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: nkrokhmal
  POSTGRES_PASSWORD: kloppolk_2018
