apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres
spec:
   serviceName: "postgres"
   replicas: 2
   selector:
     matchLabels:
       app: postgres
   template:
     metadata:
       name: postgres
       labels:
          app: postgres
     spec:
       containers:
       - name: postgres
         image: postgres:10.4
         imagePullPolicy: "IfNotPresent"
         ports:
         - containerPort: 5432
         envFrom:
         - configMapRef:
             name: postgres-config
         volumeMounts:
         - mountPath: /var/lib/postgresql/data
           name: postgresdb
           subPath: postgres
       volumes:
       - name: postgresdb
         persistentVolumeClaim:
           claimName: postgres-pvc


