apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
data:
  filebeat.yaml: |-
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/saved_logs/*.txt
      fields_under_root: true
      json.keys_under_root: true
      processors:
        - timestamp:
            field: date
            layouts:
              - '2006-01-02T15:04:05Z'
              - '2006-01-02T15:04:05.999Z'
            test:
              - '2019-06-22T16:33:51Z'
              - '2019-11-18T04:59:51.123Z'
        - drop_fields:
            fields: [date]
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                # logs_path: "/var/log/containers/"        
                logs_path: "/var/log/saved_logs/"
    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
